# Generated by Django 5.0.6 on 2024-11-04 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CursoColegio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=1)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Alumno'), ('teacher', 'Profesor'), ('admin', 'Administrador')], default='student', max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('colegio', models.ForeignKey(blank=True, help_text='Solo aplicable si el usuario es profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='api.colegio')),
                ('curso', models.ForeignKey(blank=True, help_text='Aplicable si el usuario es alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='api.cursocolegio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
