# Generated by Django 5.0.6 on 2024-11-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_colegio_cursocolegio_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminospareados',
            name='uso',
            field=models.CharField(default='conceptos', max_length=255),
            preserve_default=False,
        ),
    ]
