# Generated by Django 3.2 on 2024-10-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241016_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
