# Generated by Django 5.0.6 on 2024-11-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_etapas_componente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceEstudiantes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiempo', models.DurationField(help_text='Tiempo invertido en la etapa')),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('logro', models.PositiveIntegerField(help_text='Porcentaje de logro alcanzado en la etapa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='api.profile')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='api.etapas')),
            ],
        ),
    ]
