# Generated by Django 5.1.3 on 2024-11-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241018_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('componente', models.TextField()),
                ('completado', models.BooleanField(default=False)),
                ('posicion_x', models.IntegerField()),
                ('posicion_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id_nivel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OA',
            fields=[
                ('id_OA', models.AutoField(primary_key=True, serialize=False)),
                ('OA', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TerminosPareados',
            fields=[
                ('id_termino', models.AutoField(primary_key=True, serialize=False)),
                ('uso', models.CharField(max_length=255)),
                ('concepto', models.CharField(max_length=255)),
                ('definicion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AvanceEstudiantes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiempo', models.DurationField(help_text='Tiempo invertido en la etapa')),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('logro', models.PositiveIntegerField(help_text='Porcentaje de logro alcanzado en la etapa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='api.profile')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='api.etapas')),
            ],
        ),
        migrations.AddField(
            model_name='etapas',
            name='id_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.niveles'),
        ),
        migrations.AddField(
            model_name='niveles',
            name='OA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.oa'),
        ),
        migrations.CreateModel(
            name='IndicadoresEvaluacion',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('id_OA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.oa')),
            ],
        ),
        migrations.AddField(
            model_name='etapas',
            name='OA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.oa'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('dificultad', models.CharField(max_length=50)),
                ('habilidad', models.CharField(max_length=50)),
                ('configuracion', models.JSONField(blank=True, null=True)),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etapas')),
            ],
        ),
    ]
